openapi: 3.0.3
info:
  title: Slop Video Assembly API
  description: |
    Backend API for FFmpeg video assembly. Receives generated images and audio files,
    assembles them into a video using FFmpeg, and returns the final video file.
  version: 1.0.0
  contact:
    name: Slop Video Generator

servers:
  - url: https://slop-video-backend-{project-hash}.run.app
    description: Cloud Run production
  - url: http://localhost:8000
    description: Local development

paths:
  /health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      description: Returns service health status for load balancer
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  version:
                    type: string
                required:
                  - status

  /assemble-video:
    post:
      operationId: assembleVideo
      summary: Assemble video from images and audio
      description: |
        Accepts images and audio files as multipart form data, uses FFmpeg to:
        1. Create a video from images with specified durations
        2. Concatenate audio files
        3. Merge video and audio tracks
        4. Return the final MP4 video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                metadata:
                  type: string
                  description: JSON-encoded assembly metadata
                  example: |
                    {
                      "scenes": [
                        {"index": 0, "imageDuration": 10.5},
                        {"index": 1, "imageDuration": 8.2}
                      ],
                      "resolution": {"width": 1024, "height": 1536},
                      "frameRate": 24
                    }
                images:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Image files in scene order (image_0.png, image_1.png, ...)
                audio:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Audio files in scene order (audio_0.mp3, audio_1.mp3, ...)
              required:
                - metadata
                - images
                - audio
      responses:
        '200':
          description: Video assembled successfully
          content:
            video/mp4:
              schema:
                type: string
                format: binary
          headers:
            X-Video-Duration:
              description: Video duration in seconds
              schema:
                type: number
            Content-Disposition:
              description: Suggested filename
              schema:
                type: string
                example: attachment; filename="slop-video-2025-11-26.mp4"
        '400':
          description: Invalid request (missing files, invalid metadata)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '413':
          description: Request too large (exceeded file size limits)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: FFmpeg processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '504':
          description: Processing timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AssemblyMetadata:
      type: object
      properties:
        scenes:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
                description: Scene order (0-based)
              imageDuration:
                type: number
                description: Duration to display this image in seconds
            required:
              - index
              - imageDuration
        resolution:
          type: object
          properties:
            width:
              type: integer
              description: Video width in pixels
            height:
              type: integer
              description: Video height in pixels
          required:
            - width
            - height
        frameRate:
          type: integer
          description: Video frame rate (FPS)
          default: 24
      required:
        - scenes
        - resolution

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error type
          enum:
            - INVALID_REQUEST
            - MISSING_FILES
            - INVALID_METADATA
            - FILE_TOO_LARGE
            - FFMPEG_ERROR
            - TIMEOUT
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error context
          additionalProperties: true
      required:
        - error
        - message

# Security: No authentication required - video assembly is stateless
# Rate limiting handled by Cloud Run scaling
